### PR TITLE
allow NAETHER_MIRROR to override maven repo to bootstrap jars from

### PR DESCRIPTION
**Pull request by mguymon**
@r6p Improvement for #18

### CODE REVIEW

**Comment by r6p** [comment]
Thank you! Do you have cycles to push a 0.13.9 release to rubygems.org?

**Comment by r6p** [comment]
So since we use naether by way of lock_jar the transitive dependency won't resolve 0.14.0, since lock_jar has a runtime dependency of naether ~> 0.13.8. Any thoughts on how to resolve that? I guess new version of the lock_jar gem is a requirement at this point.

**Comment by mguymon** [comment]
yeah, I can bump lock_jar to 0.14.0

**Comment by mguymon** [comment]
released lock_jar 0.10.5 with naether dep of 0.14.0

**Comment by r6p** [comment]
Awesome! I'll take it for a spin and let you know. Thanks SO much for turning this around SO quickly!!!

**Pull request merged**
